version: "3"
services:
  app:
    image: rate-limiter
    restart: unless-stopped
    container_name: rate-limiter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1111:1111
    depends_on:
      - cache
  cache:
    image: redis:7.0.8-alpine
    container_name: cache
    command:
      - redis-server
      - --save
      - "20"
      - "1"
      - --loglevel
      - warning
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis-data:/data
volumes:
  redis-data:
